# Site
name: "TechPulseToday"
title: "TechPulseToday"
description: "Taking Web Out Of The Box"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
url: "https://www.techpulsetoday.com"
google_analytics: 'UA-86476619-1'
disqus: 'techpulsetoday'
mailchimp-list: 'https://techpulsetoday.us3.list-manage.com/subscribe/post?u=87d0cb708fb9dc3a0a2baeb94&id=de6efaf6d4'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  vijayan:
    name: Vijayan
    display_name: Vijayan
    avatar: 'assets/images/45014b6c845c622ea05e73ffb9927d6a.jpeg'
    gravatar: 45014b6c845c622ea05e73ffb9927d6a
    email: techpulsetoday@gmail.com
    web: https://in.linkedin.com/in/viji5052
    twitter: https://twitter.com/techpulsetoday
    description: "Thanks for stopping by guys! I'm Vijayan and Techpulse is my beloved brainchild. Currently working as a PHP developer in a digital marketing start-up, I'm overly passionate about not just learning new things but also putting those into practice. I swear by a quote I once came across... 'What separates successful people from unsuccessful people is the former's ability to execute'. Feel free to reach out to me if you have any questions, suggestions or feedback. Hoping to see more of you here!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gist

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
